# !/bin/bash
sudo xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app

EXTENSIONS=(
    13xforever.language-x86-64-assembly
    aaron-bond.better-comments
    abadi199.elm-format
    abusaidm.html-snippets
    adambaldwin.vscode-nsp
    akamud.vscode-theme-onedark
    AlanWalk.markdown-toc
    alefragnani.Bookmarks
    alefragnani.project-manager
    alefragnani.read-only-indicator
    annsk.alignment
    anseki.vscode-color
    arcanis.vscode-zipfs
    astallinger.sourcetrail
    attilabuti.vscode-mjml
    austin.code-gnu-global
    azaugg.vscode-python-docstring
    Azurite.azurite
    bajdzis.vscode-database
    bengreenier.vscode-node-readme
    bradlc.vscode-tailwindcss
    bungcip.better-toml
    christian-kohler.npm-intellisense
    christian-kohler.path-intellisense
    codezombiech.gitignore
    cospaia.calva-fmt
    cospaia.clojure4vscode
    cospaia.paredit-revived
    cspotcode.vscode-mocha-latte
    dariofuzinato.vue-peek
    DavidAnson.vscode-markdownlint
    dbaeumer.jshint
    dbaeumer.vscode-eslint
    dbankier.vscode-instant-markdown
    devCAT.lua-debug
    dexterhaslem.factor
    dkundel.vscode-npm-source
    donjayamanne.githistory
    DotJoshJohnson.xml
    doublefint.pgsql
    DSKWRK.vscode-generate-getter-setter
    eamodio.gitlens
    ecmel.vscode-html-css
    eg2.tslint
    eg2.vscode-npm-script
    EQuimper.react-native-react-redux
    eriklynd.json-tools
    esbenp.prettier-vscode
    felipecaputo.git-project-manager
    file-icons.file-icons
    fknop.vscode-npm
    formulahendry.auto-close-tag
    formulahendry.auto-complete-tag
    formulahendry.auto-rename-tag
    formulahendry.code-runner
    foxundermoon.shell-format
    fttx.language-forth
    gccfeli.vscode-lua
    gencer.html-slim-scss-css-class-completion
    gerane.Theme-TomorrowNight
    GitHub.remotehub
    GitHub.vscode-pull-request-github
    GrapeCity.gc-excelviewer
    Gruntfuggly.todo-tree
    hashicorp.terraform
    hbenl.vscode-test-explorer
    himanoa.Python-autopep8
    hollowtree.vue-snippets
    HookyQR.beautify
    humao.rest-client
    iampeterbanjo.elixirlinter
    IBM.output-colorizer
    ionutvmi.path-autocomplete
    jakebathman.mysql-syntax
    JakeBecker.elixir-ls
    janisdd.vscode-edit-csv
    jasonnutter.search-node-modules
    jebbs.plantuml
    jgw9617.ionic2-vscode
    joelday.docthis
    johnpapa.vscode-peacock
    johnsoncodehk.volar
    johnsoncodehk.vscode-typescript-vue-plugin
    joshjg.vscode-credo
    joshpeng.theme-onedark-sublime
    jpoissonnier.vscode-styled-components
    kalitaalexey.vscode-rust
    keyring.Lua
    kisstkondoros.vscode-codemetrics
    kruemelkatze.vscode-dashboard
    kumar-harsh.graphql-for-vscode
    leizongmin.node-module-intellisense
    littlefoxteam.vscode-python-test-adapter
    liuji-jim.vue
    mechatroner.rainbow-csv
    mhutchie.git-graph
    micnil.vscode-checkpoints
    mikestead.dotenv
    mindaro-dev.file-downloader
    mindaro.mindaro
    miramac.vscode-exec-node
    mirao.mads
    mitaki28.vscode-clang
    mitchdenny.ecdc
    moozzyk.Arduino
    mrmlnc.vscode-attrs-sorter
    mrmlnc.vscode-duplicate
    mrorz.language-gettext
    ms-azure-devops.azure-pipelines
    ms-azuretools.vscode-azureresourcegroups
    ms-azuretools.vscode-azurestorage
    ms-azuretools.vscode-docker
    ms-dotnettools.csharp
    ms-dotnettools.vscode-dotnet-runtime
    ms-kubernetes-tools.vscode-aks-tools
    ms-kubernetes-tools.vscode-kubernetes-tools
    ms-mssql.data-workspace-vscode
    ms-mssql.mssql
    ms-mssql.sql-database-projects-vscode
    ms-ossdata.vscode-postgresql
    ms-python.python
    ms-python.vscode-pylance
    ms-toolsai.jupyter
    ms-toolsai.jupyter-keymap
    ms-toolsai.jupyter-renderers
    ms-vscode-remote.remote-containers
    ms-vscode-remote.remote-ssh
    ms-vscode-remote.remote-ssh-edit
    ms-vscode-remote.remote-ssh-explorer
    ms-vscode-remote.remote-wsl
    ms-vscode-remote.vscode-remote-extensionpack
    ms-vscode.azure-account
    ms-vscode.azurecli
    ms-vscode.cpptools
    ms-vscode.node-debug2
    ms-vscode.test-adapter-converter
    ms-vscode.Theme-TomorrowKit
    ms-vscode.vscode-js-profile-flame
    ms-vscode.vscode-typescript-tslint-plugin
    ms-vsliveshare.vsliveshare
    ms-vsliveshare.vsliveshare-audio
    msjsdiag.cordova-tools
    msjsdiag.debugger-for-chrome
    msjsdiag.vscode-react-native
    msrvida.vscode-sanddance
    mtxr.sqltools
    mubaidr.vuejs-extension-pack
    nadako.vshaxe
    nicollasr.vscode-streamdeck
    NigelRook.vscode-linter-erlc
    octref.vetur
    openfl.lime-vscode-extension
    Orta.vscode-jest
    patbenatar.advanced-new-file
    pgourlain.erlang
    phoenixframework.phoenix
    PKief.material-icon-theme
    prime31.zig
    qezhu.gitlink
    qinjia.view-in-browser
    quicktype.quicktype
    rbbit.typescript-hero
    rebornix.ruby
    redhat.java
    redhat.vscode-commons
    redhat.vscode-yaml
    RedVanWorkshop.explorer-exclude-vscode-extension
    richie5um2.vscode-sort-json
    ritwickdey.LiveServer
    robertoachar.vscode-essentials-snippets
    rogalmic.bash-debug
    Rubymaniac.vscode-html-to-elm
    ryu1kn.partial-diff
    samuelcolvin.jinjahtml
    sandcastle.whitespace
    sandy081.todotasks
    saratravi.elixir-formatter
    saviorisdead.RustyCode
    sbrink.elm
    sdras.vue-vscode-snippets
    sensourceinc.vscode-sql-beautify
    Shan.code-settings-sync
    shanoor.vscode-nginx
    shinnn.standard
    shinnn.stylelint
    sleistner.vscode-fileutils
    slevesque.shader
    slevesque.vscode-hexdump
    stefanjarina.vscode-eex-snippets
    stevencl.addDocComments
    stkb.rewrap
    streetsidesoftware.code-spell-checker
    stripe.vscode-stripe
    stuart.unique-window-colors
    sumneko.lua
    tiehuis.zig
    tomoki1207.pdf
    tomsaunders.vscode-workspace-explorer
    vilicvane.es-quotes
    VisualStudioExptTeam.vscodeintellicode
    vladmrnv.expresssnippet
    vsciot-vscode.vscode-arduino
    vscjava.vscode-java-debug
    vscjava.vscode-java-dependency
    vscjava.vscode-java-pack
    vscjava.vscode-java-test
    vscjava.vscode-maven
    vscode-icons-team.vscode-icons
    vshaxe.haxe-checkstyle
    vsls-contrib.gistfs
    waderyan.gitblame
    wayou.vscode-todo-highlight
    wiggin77.codedox
    wingrunr21.vscode-ruby
    wix.vscode-import-cost
    wmaurer.change-case
    xabikos.JavaScriptSnippets
    xxxg0001.lua-for-vscode
    ymotongpoo.licenser
    yuce.erlang-otp
    yzane.markdown-pdf
    yzhang.markdown-all-in-one
    zhuangtongfa.material-theme
    Zignd.html-css-class-completion
)

for extension in "${EXTENSIONS[@]}"; do
    code --install-extension $extension
done

cp ./vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
